[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
optimizer = true

[rpc_endpoints]
hedera = "https://ancient-fluent-tree.hedera-testnet.quiknode.pro/352ada59732a45c5f508afe8fbed229040ccefbc"

